"""Designs for every Cubelings creature after zone 1 (zone 1 lives in cubelings.py).

Every creature is the same rounded cube; what changes is the color and the parts on top:
ears / head piece, eye style, nose, mouth, features, legs and tail (see the parts library in cubelings.py).
Body colors come from roblox/shared/Config/World1.luau.
"""


def face(eye="#24161C", mouth=None, blush="#FF9EB5"):
    colors = {"eye": eye, "shine": "#FFFFFF", "mouth": mouth or eye}
    if blush:
        colors["blush"] = blush
    return colors


SPECIES = {
    # ----- Zone 2: Flower Field --------------------------------------------------------------------------------------
    "Bee": {
        "colors": {"body": "#F5D246", "belly": "#FFF1B0", "legs": "#2B2433", "stripe": "#2B2433", "antenna_tip": "#2B2433", "wing": "#E9F6FF", **face()},
        "ears": "antenna",
        "mouth": "smile",
        "features": ["stripes", "wings_bee"],
        "tail": "none",
    },
    "Ladybug": {
        "colors": {"body": "#E5534B", "legs": "#2B2433", "spot": "#2B2433", "antenna_tip": "#2B2433", **face("#24141A", blush="#FF9E9E")},
        "ears": "antenna",
        "mouth": "smile",
        "features": ["spots"],
        "tail": "none",
    },
    "Butterfly": {
        "colors": {"body": "#B9A6F5", "belly": "#E8E0FF", "legs": "#5B4A8C", "wing": "#FF9ED8", "wing_spot": "#FFE27A", "antenna_tip": "#FF9ED8", "dark": "#5B4A8C", **face("#2A1F45")},
        "ears": "antenna",
        "eye_style": "sparkle",
        "mouth": "smile",
        "features": ["wings_butterfly"],
        "tail": "none",
    },
    "Uni": {
        "colors": {"body": "#F7C6E0", "belly": "#FFF0F7", "legs": "#E59BC4", "horn": "#FFE48A", "horn_line": "#F5B841", "mane": "#9FD8FF", "mane2": "#C9A8FF", **face("#3A2340")},
        "ears": "unihorn",
        "eye_style": "sparkle",
        "mouth": "smile",
        "tail": "puff",
    },
    # ----- Zone 3: Forest --------------------------------------------------------------------------------------------
    "Fox": {
        "colors": {"body": "#EB783C", "belly": "#FFF3E6", "ear_inner": "#3A2418", "legs": "#3A2418", "tail_tip": "#FFF3E6", "nose": "#2B1A12", "tongue": "#FF7A8A", **face("#2B1A12")},
        "ears": "cat",
        "nose": "oval",
        "mouth": "open",
        "tail": "fox",
    },
    "Owl": {
        "colors": {"body": "#96785F", "belly": "#E8D5BC", "legs": "#F2A93B", "tuft": "#7A5E48", "patch": "#E8D5BC", "wing": "#7A5E48", "beak": "#F2A93B", **face("#2A1C12", blush=None)},
        "ears": "tufts",
        "eyes": 1.1,
        "nose": "beak",
        "mouth": "none",
        "blush": False,
        "features": ["eye_rings", "wings_bird"],
        "tail": "none",
    },
    "Deer": {
        "colors": {"body": "#C8966E", "belly": "#F5E3CC", "legs": "#7A5236", "horn": "#F1DFC0", "ear_inner": "#F5C3B0", "spot": "#F5E3CC", "nose": "#2B1A12", **face("#24150D")},
        "ears": "antlers",
        "nose": "oval",
        "mouth": "smile",
        "features": ["spots"],
        "spot_list": [(0, 0.2, 1.0, 0, 0, 0.16), (0.4, 0.5, 1.0, 0, 0, 0.13), (-0.4, 0.55, 1.0, 0, 0, 0.13), (1.0, 0.4, 0.4, 1, 0, 0.13), (-1.0, 0.35, 0.45, 1, 0, 0.13), (1.0, 0.0, 0.6, 1, 0, 0.1), (-1.0, -0.05, 0.62, 1, 0, 0.1)],
        "tail": "nub",
    },
    "Sprout": {
        "colors": {"body": "#7BD389", "belly": "#D4F5C9", "legs": "#4E9E5B", "leaf": "#4FBF5A", "stem": "#3F8F45", **face("#1F3A22", blush="#FFB3A8")},
        "ears": "leaf",
        "eye_style": "sleepy",
        "mouth": "smile",
        "tail": "none",
    },
    # ----- Zone 4: Beach ---------------------------------------------------------------------------------------------
    "Crab": {
        "colors": {"body": "#E55A46", "belly": "#FFC9B8", "legs": "#C9432F", "claw": "#E55A46", "white": "#FFFFFF", **face("#2B1410")},
        "ears": "none",
        "eye_style": "stalk",
        "brows": None,
        "mouth": "frown",
        "legs": "crab",
        "features": ["claws"],
        "tail": "none",
    },
    "Turtle": {
        "colors": {"body": "#6EB46E", "belly": "#E6F2C2", "legs": "#4F8F4F", "shell": "#8A5E3B", "plate": "#B5834F", **face("#1F2E1F")},
        "ears": "none",
        "eye_style": "sleepy",
        "mouth": "smile",
        "features": ["shell"],
        "tail": "nub",
    },
    "Dolphin": {
        "colors": {"body": "#78A0C8", "belly": "#E3F1FF", "fin": "#5E86B0", "tongue": "#FF8FA0", **face("#1B2638")},
        "ears": "none",
        "mouth": "open",
        "legs": "none",
        "features": ["dorsal_fin", "flippers"],
        "tail": "fluke",
    },
    "Octopus": {
        "colors": {"body": "#A05AC8", "belly": "#E7C8F5", "spot": "#C989EA", **face("#2A1638")},
        "ears": "none",
        "eyes": 1.08,
        "mouth": "smile",
        "legs": "tentacles",
        "features": ["spots"],
        "spot_list": [(0, 0.1, 1.0, 0, 0, 0.22), (0.5, 0.45, 1.0, 0, 0, 0.15), (-0.5, 0.35, 1.0, 0, 0, 0.15), (1.0, 0.1, 0.35, 1, 0, 0.15), (-1.0, -0.2, 0.3, 1, 0, 0.14), (0.3, 1.0, 0.3, 2, 0, 0.17)],
        "tail": "none",
    },
    # ----- Zone 5: Mushroom Cave ---------------------------------------------------------------------------------------
    "Mushroom": {
        "colors": {"body": "#F3E3C8", "legs": "#D9C3A0", "cap": "#D74646", "spot": "#FFFFFF", **face("#3A2418", blush="#FF9E9E")},
        "ears": "cap",
        "mouth": "smile",
        "tail": "none",
    },
    "Bat": {
        "colors": {"body": "#463C5A", "belly": "#6E6388", "ear_inner": "#C98AB0", "legs": "#2E2740", "wing": "#2E2740", "dark": "#1E1A2A", "brow": "#1E1A2A", "white": "#FFFFFF", **face("#FFD84D", mouth="#1E1A2A", blush="#B07090")},
        "ears": "bat",
        "brows": "angry",
        "mouth": "fangs",
        "features": ["wings_bat"],
        "tail": "none",
    },
    "Glowworm": {
        "colors": {"body": "#B4F05A", "belly": "#E9FFC4", "legs": "#7CBF3A", "stripe": "#86C93E", "antenna_tip": "#FFF27A", "glow": "#FFF27A", "dark": "#4E7A2A", **face("#24341A")},
        "ears": "antenna",
        "eye_style": "sleepy",
        "mouth": "smile",
        "features": ["stripes", "glow_dots"],
        "stripes": [(-0.7, -0.55), (-0.3, -0.15), (0.1, 0.25), (0.5, 0.65)],
        "tail": "nub",
    },
    "Shade": {
        "colors": {"body": "#5A3C82", "belly": "#7E5DAA", "horn": "#2A1E3E", "brow": "#1A1028", **face("#E8FF6A", mouth="#1A1028", blush=None)},
        "ears": "horns",
        "brows": "angry",
        "mouth": "frown",
        "legs": "wisp",
        "blush": False,
        "tail": "none",
    },
    # ----- Zone 6: Desert ----------------------------------------------------------------------------------------------
    "Camel": {
        "colors": {"body": "#D6AA6E", "belly": "#F5E0BC", "legs": "#A87C4A", "ear_inner": "#F5E0BC", "nose": "#6B4A2E", **face("#2B1C10")},
        "ears": "none",
        "eye_style": "sleepy",
        "nose": "oval",
        "mouth": "smile",
        "features": ["hump"],
        "humps": [(-0.15, 0.62), (0.62, 0.52)],
        "tail": "nub",
    },
    "Scorpion": {
        "colors": {"body": "#8C5A32", "belly": "#C99A6A", "legs": "#6B4224", "claw": "#8C5A32", "segment": "#A8703F", "stinger": "#2B1A10", "horn": "#5A3A20", "brow": "#2B1A10", **face("#1E120A", blush=None)},
        "ears": "none",
        "brows": "angry",
        "mouth": "frown",
        "legs": "crab",
        "blush": False,
        "features": ["claws"],
        "tail": "stinger",
    },
    "Cactus": {
        "colors": {"body": "#5AAA5A", "spine": "#FFF6D8", "pot": "#C8693E", "pot_rim": "#A8552F", "flower": "#FF8FB1", "flower_center": "#FFD84D", **face("#1F3A22", blush="#FF9E9E")},
        "ears": "none",
        "eye_style": "closed",
        "mouth": "smile",
        "legs": "pot",
        "features": ["spines", "flower"],
        "tail": "none",
    },
    "Sphinx": {
        "colors": {"body": "#E6BE5A", "belly": "#F5DFA0", "legs": "#B8913A", "cloth": "#3D63C9", "cloth2": "#F5D46A", "gold": "#F5C542", "shades": "#1A1A24", **face("#2B1C10", blush=None)},
        "ears": "none",
        "eye_style": "shades",
        "mouth": "smile",
        "blush": False,
        "features": ["nemes"],
        "tail": "lizard",
    },
    # ----- Zone 7: Snow Peak -------------------------------------------------------------------------------------------
    "Penguin": {
        "colors": {"body": "#32374A", "belly": "#FFFFFF", "beak": "#F7A93B", "feet": "#F7A93B", "fin": "#252938", "patch": "#FFFFFF", **face("#16182A", blush="#FF9EB5")},
        "ears": "none",
        "nose": "beak",
        "mouth": "none",
        "legs": "feet",
        "features": ["face_patch", "flippers"],
        "tail": "none",
    },
    "Seal": {
        "colors": {"body": "#A0AAB9", "belly": "#E3E8EF", "fin": "#7E8899", "nose": "#2A2A33", "tongue": "#FF8FA0", "dark": "#4A4E5A", **face("#1E2028")},
        "ears": "none",
        "nose": "oval",
        "mouth": "open",
        "legs": "none",
        "features": ["flippers", "whiskers"],
        "tail": "fluke",
    },
    "Snowman": {
        "colors": {"body": "#F5F8FF", "legs": "#DCE3EE", "carrot": "#F28C28", "scarf": "#E5534B", "dark": "#2A2A33", **face("#2A2A33", blush="#FFC0CB")},
        "ears": "hat",
        "nose": "carrot",
        "mouth": "dots",
        "features": ["scarf", "buttons"],
        "tail": "none",
    },
    "Yeti": {
        "colors": {"body": "#EBF0FA", "belly": "#FFFFFF", "legs": "#C8D2E6", "patch": "#8FB7E8", "fur": "#FFFFFF", "horn": "#9AA6BF", "brow": "#3A4A66", "white": "#FFFFFF", **face("#1E2A40", mouth="#2A3A55", blush=None)},
        "ears": "horns",
        "brows": "angry",
        "mouth": "fangs",
        "blush": False,
        "features": ["face_patch", "fur"],
        "tail": "nub",
    },
    # ----- Zone 8: Volcano ---------------------------------------------------------------------------------------------
    "Imp": {
        "colors": {"body": "#E5534B", "belly": "#FF9E8A", "legs": "#A8302A", "horn": "#3A1A1A", "wing": "#8A2A2A", "dark": "#3A1A1A", "brow": "#3A1A1A", "white": "#FFFFFF", **face("#FFE14D", mouth="#3A1A1A", blush=None)},
        "ears": "horns",
        "brows": "angry",
        "mouth": "fangs",
        "blush": False,
        "features": ["wings_bat"],
        "tail": "devil",
    },
    "Salamander": {
        "colors": {"body": "#F57832", "belly": "#FFD07A", "legs": "#C8551F", "spot": "#FFD84D", "spike": "#FFD84D", "tongue": "#FF6A7A", **face("#2B140A")},
        "ears": "none",
        "mouth": "open",
        "features": ["spots", "back_spikes"],
        "tail": "lizard",
    },
    "Golem": {
        "colors": {"body": "#6E6964", "belly": "#8C8680", "legs": "#55504B", "rock": "#8A847E", "glow": "#FF9A3D", **face("#FF9A3D", mouth="#3A3530", blush=None)},
        "ears": "none",
        "eye_style": "square",
        "mouth": "line",
        "blush": False,
        "features": ["rocks"],
        "tail": "none",
    },
    "Phoenix": {
        "colors": {"body": "#FF8C28", "belly": "#FFD86A", "legs": "#E2582A", "flame": "#FF5A1F", "flame2": "#FFD84D", "wing": "#FF5A1F", "wing_tip": "#FFD84D", "beak": "#FFD84D", **face("#3A1A0A", blush=None)},
        "ears": "flame",
        "eye_style": "sparkle",
        "nose": "beak",
        "mouth": "none",
        "blush": False,
        "features": ["wings_bird"],
        "tail": "flame",
    },
    # ----- Zone 9: Frozen Lake -----------------------------------------------------------------------------------------
    "Ice Fox": {
        "colors": {"body": "#BEE1F5", "belly": "#FFFFFF", "ear_inner": "#7FB8E0", "legs": "#8CC0E0", "tail_tip": "#FFFFFF", "crystal": "#E6FBFF", "nose": "#3A5A78", "tongue": "#FF8FA0", **face("#1E3A55")},
        "ears": "cat",
        "nose": "oval",
        "mouth": "open",
        "features": ["crystals"],
        "crystal_list": [(0.0, -0.4, 0.35, 0), (-0.22, -0.3, 0.25, -20), (0.22, -0.3, 0.25, 20)],
        "tail": "fox",
    },
    "Narwhal": {
        "colors": {"body": "#82AADC", "belly": "#E3F0FF", "fin": "#5E86B8", "horn": "#F5F0DC", "horn_line": "#C9C0A0", "spot": "#5E86B8", **face("#1B2638")},
        "ears": "none",
        "mouth": "smile",
        "legs": "none",
        "features": ["tusk", "flippers", "spots"],
        "spot_list": [(0.3, 0.3, 1.0, 0, 0, 0.12), (-0.4, 0.5, 1.0, 0, 0, 0.1), (1.0, 0.3, 0.4, 1, 0, 0.1), (-1.0, 0.2, 0.35, 1, 0, 0.1)],
        "tail": "fluke",
    },
    "Frost Owl": {
        "colors": {"body": "#DCEBFA", "belly": "#FFFFFF", "legs": "#9FC4E8", "tuft": "#B8D6F2", "patch": "#FFFFFF", "wing": "#B8D6F2", "wing_tip": "#E6F4FF", "beak": "#7FB0E0", "crystal": "#E6FBFF", **face("#1E3A66", blush=None)},
        "ears": "tufts",
        "eyes": 1.1,
        "eye_style": "sparkle",
        "nose": "beak",
        "mouth": "none",
        "blush": False,
        "features": ["eye_rings", "wings_bird"],
        "tail": "none",
    },
    "Ice Dragon": {
        "colors": {"body": "#78D2EB", "belly": "#D8F6FF", "legs": "#4FA8C8", "horn": "#E6FBFF", "wing": "#4FA8C8", "spike": "#E6FBFF", "brow": "#1E4A66", "white": "#FFFFFF", **face("#13314A", mouth="#13314A", blush=None)},
        "ears": "horns",
        "brows": "angry",
        "mouth": "fangs",
        "blush": False,
        "features": ["wings_dragon", "back_spikes"],
        "tail": "dragon",
    },
    # ----- Zone 10: Pixel Zone -----------------------------------------------------------------------------------------
    "Bot": {
        "colors": {"body": "#9AA5B1", "belly": "#C8D0D9", "legs": "#6E7884", "screen": "#16202E", "metal": "#6E7884", "antenna_tip": "#FF5A5A", "dark": "#4A525C", "eye": "#5BF0FF", "shine": "#FFFFFF", "mouth": "#5BF0FF"},
        "ears": "antenna",
        "eye_style": "square",
        "mouth": "line",
        "blush": False,
        "features": ["screen", "bolts"],
        "tail": "none",
    },
    "Byte": {
        "colors": {"body": "#8E5BD9", "belly": "#C3A2F0", "legs": "#6A3FB0", "accent": "#5BF0FF", "accent2": "#FF6AD5", **face("#1A1030", blush="#FF8FD0")},
        "ears": "none",
        "eye_style": "square",
        "mouth": "smile",
        "features": ["voxels"],
        "tail": "none",
    },
    "Cursor": {
        "colors": {"body": "#F0F0F0", "belly": "#FFFFFF", "legs": "#C8C8D0", "white": "#FFFFFF", "dark": "#1E1E24", **face("#1E1E24", blush="#FFB3C6")},
        "ears": "none",
        "eye_style": "square",
        "mouth": "smile",
        "features": ["cursor"],
        "tail": "none",
    },
    "King": {
        "colors": {"body": "#6C63D9", "belly": "#B3ACF5", "legs": "#4A42A8", "gold": "#F5C542", "gem": "#E5534B", "gem2": "#5BF0FF", "cape": "#C9303E", "white": "#FFFFFF", "shades": "#14141E", **face("#14141E", blush=None)},
        "ears": "crown",
        "eye_style": "shades",
        "mouth": "smile",
        "blush": False,
        "features": ["cape"],
        "tail": "none",
    },
}

ZONES = [
    ["Cubby", "Kitty", "Bunny", "Bear"],
    ["Bee", "Ladybug", "Butterfly", "Uni"],
    ["Fox", "Owl", "Deer", "Sprout"],
    ["Crab", "Turtle", "Dolphin", "Octopus"],
    ["Mushroom", "Bat", "Glowworm", "Shade"],
    ["Camel", "Scorpion", "Cactus", "Sphinx"],
    ["Penguin", "Seal", "Snowman", "Yeti"],
    ["Imp", "Salamander", "Golem", "Phoenix"],
    ["Ice Fox", "Narwhal", "Frost Owl", "Ice Dragon"],
    ["Bot", "Byte", "Cursor", "King"],
]
